version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
    volumes:
      - ./app:/usr/src/app
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=myrootpassword
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
